# Script de Deploy para Hostgator
# Execute este script após fazer o build do projeto

echo "=== ARQUIVOS PARA DEPLOY NO HOSTGATOR ==="
echo ""
echo "📁 Estrutura de arquivos necessários:"
echo "├── .next/ (pasta completa do build)"
echo "├── app/ (pasta completa da aplicação)"
echo "├── components/ (pasta completa dos componentes)"
echo "├── lib/ (pasta completa das bibliotecas)"
echo "├── public/ (pasta completa dos arquivos públicos)"
echo "├── .htaccess"
echo "├── app.json"
echo "├── next.config.mjs"
echo "├── package.json"
echo "├── package-lock.json"
echo "├── server.js"
echo "└── DEPLOY-HOSTGATOR.md (instruções)"
echo ""
echo "⚠️  NÃO ENVIE ESTES ARQUIVOS:"
echo "├── node_modules/ (será reinstalado no servidor)"
echo "├── .env.local (configure no painel do Hostgator)"
echo "├── .git/ (não necessário)"
echo "└── README.md (opcional)"
echo ""
echo "🔧 PRÓXIMOS PASSOS:"
echo "1. Comprima todos os arquivos listados acima"
echo "2. Faça upload para o Hostgator"
echo "3. Configure Node.js no cPanel"
echo "4. Configure as variáveis de ambiente"
echo "5. Execute 'npm install --production'"
echo "6. Inicie a aplicação"
echo ""
echo "📋 Variáveis de ambiente necessárias no Hostgator:"
echo "- NODE_ENV=production"
echo "- SENDGRID_API_KEY"
echo "- NEXT_PUBLIC_EMAILJS_USER_ID"
echo "- NEXT_PUBLIC_EMAILJS_SERVICE_ID"
echo "- NEXT_PUBLIC_EMAILJS_TEMPLATE_ID"
echo "- NEXT_PUBLIC_EMAILJS_PUBLIC_KEY"
echo "- NEXT_PUBLIC_EMAILJS_PRIVATE_KEY"
echo "- CRON_SECRET"
echo "- MONGODB_URI"
echo "- EMAIL_USER"
echo "- EMAIL_PASS"
